# Controller generated by Typus, use it to extend admin functionality.
class Admin::TypusUsersController < Admin::MasterController

=begin

  ##
  # You can overwrite any Admin::MasterController methods.
  #
  def index
  end

=end

=begin

  ##
  # You can extend Admin::MasterController with your methods.
  #
  # This actions have to be defined in <tt>config/typus/application.yml</tt>.
  #
  #   TypusUser:
  #     actions:
  #       index: custom_action
  #       edit: custom_action_for_an_item
  #
  def custom_action
  end

  def custom_action_for_an_item
  end

=end

end
