
Form:
  fields:
    list: id, user, title, description, deleted_at, submit_title
    form: user, title, description, fields, deleted_at, style, submit_title
    show: id, user, title, description, created_at, updated_at, fields, deleted_at, style, submit_title
    relationship:
    options:
      auto_generated:
      read_only:
      selectors:
  actions:
    index:
    edit:
  export:
  order_by:
  relationships: messages, user
  filters:
  search:
  application: freeforms
  description:

User:
  fields:
    list: id, email, created_at, activated_at, activated?
    form: email, password, password_confirmation, activated?
    show: id, email, login_count, failed_login_count, last_request_at, current_login_at, last_login_at, current_login_ip, last_login_ip, created_at, updated_at, activated_at
    relationship:
    options:
      auto_generated:
      read_only:
      selectors:
      booleans:
  actions:
    index:
    edit:
  export:
  order_by:
  relationships: forms, messages
  filters: active?
  search: email
  application: freeforms
  description:

Message:
  fields:
    list: id, user, token, read_at, form
    form: user, token, read_at, form, data
    show: id, user, token, read_at, created_at, updated_at, form, data
    relationship:
    options:
      auto_generated:
      read_only:
      selectors:
  actions:
    index:
    edit:
  export:
  order_by:
  relationships: form, user
  filters:
  search:
  application: freeforms
  description:

