javascripts:
- app:
  - jquery
  - jquer
  - jquery-cookie
  - jquery-validate
  - jquery-colorpicker
  - tools.tabs-1.0.1
  - flexigrid
  - jrails
  - application
  - editor
stylesheets:
- app:
  - common
  - layout
  - ui
  - forms
  - flexigrid
  - forms/default
  - editor