javascripts:
- app:
  - lib/jquery
  - lib/jquery-cookie
  - lib/jquery-validate
  - lib/jquery-colorpicker
  - lib/ui.core
  - lib/ui.draggable
  - lib/ui.sortable
  - lib/tools.tabs-1.0.1
  - lib/flexigrid
  - lib/jrails
  - application
  - editor
stylesheets:
- app:
  - common
  - layout
  - ui
  - forms
  - flexigrid
  - forms/default
  - editor